name: BUILD AND FIREBASE DEPLOY

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '8.x'
    - name: Build
      run: |
        npm install
        npm run build
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.firebaseKey }}    
